[package]
name = "galemind"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.37"
tokio = { version = "1.45.0", features = ["rt-multi-thread", "macros", "net"] }
tonic = "0.11"
prost = "0.12"
prost-types = "0.12"

[build-dependencies]
tonic-build = "0.11"
prost-build = "0.12"
